### ISSUE TITLE
Exception IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by rohitpal99** [mitallast/scala-nsq#4]
Using config 

```
nsq {
  lookup-address = [
    "http://127.0.0.1:xxxx"
  ]
}
```

```
[error] (run-main-1e) java.lang.IllegalArgumentException: bound must be positive
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at scala.util.Random.nextInt(Random.scala:66)
	at com.github.mitallast.nsq.NSQNettyClient$NSQNettyPool$class.connection(NSQNettyClient.scala:532)
	at com.github.mitallast.nsq.NSQNettyClient$NSQNettyProducer.connection(NSQNettyClient.scala:650)
	at com.github.mitallast.nsq.NSQNettyClient$NSQNettyProducer.pub(NSQNettyClient.scala:664)
	at com.github.mitallast.nsq.NSQProducer$class.pubStr(NSQClient.scala:55)
	at com.github.mitallast.nsq.NSQNettyClient$NSQNettyProducer.pubStr(NSQNettyClient.scala:650)
	at com.company.Main$.main(Main.scala:27)
	at com.company.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

I am getting Exception. I tried debugging the code as well.and it turns out _poolMap_ never gets initialized.

```
private val poolMap = new AbstractChannelPoolMap[SocketAddress, FixedChannelPool]
```

Am i missing something. Please suggest.

**Comment by mitallast** [comment]
Yep, there's an error in client if pool is empty.

Most likely, the `nsqlookupd` does not see `nsqd` nodes, and returns an empty response, so the connection pool is empty.

Check nsqd configuration options, like a `-broadcast-address`. Check using http port for `nsqlookupd` in client, not tcp

Try get manually list of nodes from nsqlookupd:
```
curl -XGET "http://127.0.0.1:4161"
```

**Comment by rohitpal99** [comment]
Thanks so much replying

Here is my output from `docker ps`

```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                                            NAMES
b5903d9fdb36        nsqio/nsq                "/nsqlookupd"            18 seconds ago      Up 15 seconds       4150-4151/tcp, 4170-4171/tcp, 0.0.0.0:32781->4160/tcp, 0.0.0.0:32780->4161/tcp   nsqtest_nsqlookupd_1
f631d7ea19bb        nsqtest_reader-service   "npm start"              18 seconds ago      Up 15 seconds       0.0.0.0:3000->3000/tcp                                                           reader-service
c870287b66d1        nsqio/nsq                "/nsqadmin --lookupd-"   18 seconds ago      Up 16 seconds       4150-4151/tcp, 4160-4161/tcp, 4170/tcp, 0.0.0.0:32782->4171/tcp                  nsqtest_nsqadmin_1
ddf7a382f454        nsqio/nsq                "/nsqd --lookupd-tcp-"   18 seconds ago      Up 13 seconds       4160-4161/tcp, 4170-4171/tcp, 0.0.0.0:32779->4150/tcp, 0.0.0.0:32778->4151/tcp   nsqtest_nsqd_1
f82b640e025c        nsqtest_writer-service   "npm start"              18 seconds ago      Up 14 seconds       0.0.0.0:3001->3000/tcp                                                           writer-service
```

My scala code
```
NSQClient(conf).producer().pubStr("sample_topic", data="some test data").onComplete { event =>
      event match {
        case Success(value) => print("message pub successfully")
        case Failure(error) => print("message pub failed", error)
      }
    }
```

`curl -XGET http://0.0.0.0:32780/nodes` results in
```
{
   "producers":[
      {
         "remote_address":"172.19.0.4:57868",
         "hostname":"ddf7a382f454",
         "broadcast_address":"ddf7a382f454",
         "tcp_port":4150,
         "http_port":4151,
         "version":"1.0.0-compat",
         "tombstones":[
            false
         ],
         "topics":[
            "sample_topic"
         ]
      }
   ]
}
```

**Comment by mitallast** [comment]
Check your `-broadcast-address` for `nsqd` - in your curl result `ddf7a382f454`, but you run scala outside of docker env, and maybe it's not a valid/resolved hostmane for your localhost

**Comment by mitallast** [comment]
I found that nsqlookupd changes signature for `/nodes` request.
Try release scala-nsq 1.11 from maven!

**Comment by rohitpal99** [comment]
@mitallast - Thanks for the release. But unfortunately problem still persists

I tried moving scala code inside docker env and problem still persists.
Here is my repo of code I am using.

`https://github.com/rohitpal99/nsq-docker-projects`

Please suggests if you find anything wrong. Thanks for your support.

**Comment by mitallast** [comment]
See pull request.
Read more about networking, docker, docker networking, docker networking in compose mode.
If you publish port from container to localhost, it does not mean that you publish it for all containers.
Container's localhost is not your laptop localhost, it's two different environments!

**Comment by rohitpal99** [comment]
Thanks for your help & suggestions.
